from . import (hospital_disease,
               hospital_person,
               hospital_doctor,
               hospital_patient,
               hospital_contact_person,
               hospital_diagnosis,
               hospital_patient_visit,
               hospital_doctor_change,
               hospital_doctor_schedule,
               hospital_change_doctor_multi_wizard,
               hospital_change_doctor_appointment_wizard,
               hospital_fill_doctor_schedule_wizard)
